imie=input("Jak masz na imię? ")
print("Czesc, ")
print(imie[0].upper())
print(imie[1].upper())
print(imie[2].upper())
print(imie[3].upper())
print(imie[4].upper())
dlugosc_nazwiska=len(imie)
print("Twoje imię ma")
print(dlugosc_nazwiska)
print("znaków.")