imie = input("Jak masz na imię? ")
dlugosc_imienia = len(imie)
print("Czesc, ")
print(imie[0].upper())
print(imie[1].upper())
print(imie[2].upper())
print(imie[3].upper())
print(imie[4].upper())
print("Twoje imię ma" + dlugosc_imienia + "znaków.")
